#!/usr/bin/perl
use strict;
use warnings;
use utf8;

binmode(STDOUT, ':utf8');

my $upower;
my $percent;
my $bat_state;
my $status;
my $ac_adapt;
my $full_text;
my $label;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

open (UPOWER, "upower -i /org/freedesktop/UPower/devices/battery_BAT$bat_number | grep 'percentage' |") or die;
$upower = <UPOWER>;
close(UPOWER);

if ($upower !~ /:          (\d+)%/) {
    die "$upower\n";
}

$percent = $1;
$full_text = "$percent%";

open (BAT_STATE, "upower -i /org/freedesktop/UPower/devices/battery_BAT$bat_number | grep 'state' |") or die;
$bat_state = <BAT_STATE>;
close(BAT_STATE);

if ($bat_state !~ /:               (\w+)/) {
    die "$bat_state\n";
}
$status = $1;

# Charging indicator
if ($status eq 'charging') {
    $full_text .= '󱐋';
}

if ($percent < 20) {
  $label = '󰂎';
} elsif ($percent < 45) {
  $label = '󰁺';
} elsif ($percent < 70) {
  $label = '󰁿';
} elsif ($percent < 95) {
  $label = '󰂁';
} else {
  $label = '󰁹';
}

# Output with polybar formatting
if ($status eq 'discharging') {
    if ($percent < 20) {
        print "%{F#E82424}$label $full_text%{F-}\n";  # samuraiRed
    } elsif ($percent < 40) {
        print "%{F#FFA066}$label $full_text%{F-}\n";  # surimiOrange
    } elsif ($percent < 60) {
        print "%{F#DCA561}$label $full_text%{F-}\n";  # autumnYellow
    } elsif ($percent < 85) {
        print "%{F#98BB6C}$label $full_text%{F-}\n";  # springGreen
    } else {
        print "$label $full_text\n";
    }
} else {
    print "$label $full_text\n";
}

exit(0);

