#!/bin/bash

# Check if the '-s' flag was passed to the script.
if [ "$1" = "-s" ]; then
  # If '-s' is present, change the wallpaper on the secondary screen.
  /usr/bin/nitrogen --head=1 --set-auto --save --random ~/personal/Pictures/wallpapers/vertical/ > /dev/null
else
  # If '-s' is not present, change the wallpaper on the primary screen.
  /usr/bin/nitrogen --head=0 --set-zoom-fill --save --random ~/personal/Pictures/wallpapers/horizontal/ > /dev/null
fi

