# Font settings
	font_family CaskaydiaCove Nerd Font
	bold_font auto
	italic_font auto
	bold_italic_font auto
	# font_size 13.0
	# font size for laptop
	font_size 16.0

# Cursor settings
	cursor_shape block
	cursor_blink_interval -1
	shell_integration no-cursor # Prevents p10k from setting beam cursor

# Mouse cursor settings
	mouse_hide_wait 0

# Keyboard mapping settings
		kitty_mod alt
	# Scrolling
		map alt+shift+k scroll_page_up
		map alt+shift+j scroll_page_down
	# Window management
		map alt+f move_window_to_top
		map alt+enter launch --cwd=current
	# Tab management
		map alt+t new_tab
		map alt+q close_tab
		map alt+n next_tab
		map alt+p previous_tab
		map alt+shift+t set_tab_title
	# Change window layout
		map alt+shift+l next_layout
	# Reload config file
		map alt+shift+r load_config_file
	# Clipboard management
		map ctrl+shift+c copy_to_clipboard
		map ctrl+shift+v paste_from_clipboard
	# Open file manager in new window
	# Requires ranger terminal file manager
		map alt+g launch ranger
	# Resolves vim split navigation conflict
		map alt+h noop
		map alt+j noop
		map alt+k noop
		map alt+l noop

# Terminal bell settings
	enable_audio_bell no

# Window settings
	window_padding_width 5

# Split screen tabs settings
enabled_layouts tall:bias=50;full_size=1;mirrored=false

┌──────────────┬───────────────┐
│              │               │
│              │               │
│              │               │
│              ├───────────────┤
│              │               │
│              │               │
│              │               │
│              ├───────────────┤
│              │               │
│              │               │
│              │               │
└──────────────┴───────────────┘

# Tab ui properties
	tab_bar_edge top
	tab_bar_align left
	tab_bar_style powerline
	tab_powerline_style slanted
	tab_title_template "{index}:{title}"

# Appearance settings
	background_opacity 0.8
	background_blur 1

# Colorschemes
# Basically Japanesque with
# selection backround and
# cursor color swapped
#
# Original Japanesque config:
#
# https://github.com/dexpota/kitty-themes/blob/master/themes/Japanesque.conf
background            #1d1d1d
foreground            #f7f6ec
cursor                #155776
selection_background  #eccf4f
color0                #343835
color8                #585a58
color1                #ce3e60
color9                #d18ea6
color2                #7bb75b
color10               #767e2b
color3                #e8b32a
color11               #77592e
color4                #4c99d3
color12               #135879
color5                #a57fc4
color13               #5f4190
color6                #389aac
color14               #76bbca
color7                #f9faf6
color15               #b1b5ae
selection_foreground #1d1d1d
