background {
    monitor =
    path = /home/edbar/Pictures/wallpapers/horizontal/miquella.png
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
    ignore_empty_input = true
}

# Left panel strip
shape {
    monitor =
    size = 400, 4000
    color = rgba(0, 0, 0, 0.45)
    rounding = 1
    border_size = 0
    border_color = rgba(0, 0, 0, 0)
    rotate = 0
    xray = false
    position = 140, 0
    halign = left
    valign = top
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgba(224, 208, 190, 0.9)
    font_size = 40
    font_family = Caskaydia Cove NF
    position = 160, 240
    halign = left
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:60000] LC_TIME=pt_BR.UTF-8 date +"%A, %d %B %Y"
    color = rgba(224, 208, 190, 0.9)
    font_size = 19
    font_family = Caskaydia Cove NF
    position = 160, 175
    halign = left
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(947156ee) rgba(AD8B6Cee) 45deg
    check_color = rgba(CA9E70ee) rgba(905C33ee) 120deg
    fail_color = rgba(6C594Bee) rgba(0B0806ee) 40deg
    inner_color = rgba(11, 8, 6, 0.7)
    font_color = rgb(224, 208, 190)
    fade_on_empty = true
    font_family = Caskaydia Cove NF
    placeholder_text = <i><span foreground="##ffffff99">Enter your password...</span></i>
    fail_text = $PAMFAIL
    hide_input = false
    rounding = 15
    position = 160, -220
    halign = left
    valign = center
}
