[ui.window.box]
width = 700
min_width = 664
max_width = 800
height = 400
min_height = 396
max_height = 500

[ui.window.box.scroll.list]
height = 300
min_height = 300
max_height = 300

[ui.window.box.scroll.list.item.icon]
pixel_size = 40

[ui.window.box.search.spinner]
hide = true
