user: "#61afef" # bright blue (higher contrast than cyan for names)
group: "#abb2bf" # foreground

permission:
  read: "#61afef" # blue
  write: "#c678dd" # purple
  exec: "#56b6c2" # cyan
  exec-sticky: "#e06c75" # red (sticky bit stands out)
  no-access: "#e06c75" # red

date:
  hour-old: "#9aa3ad" # mid-contrast gray (readable on #282c34)
  day-old: "#7f848e" # comment gray
  older: "#5c6370" # dimmer comment gray

size:
  none: "#7f848e" # subdued, but readable
  small: "#98c379" # green
  medium: "#d19a66" # orange
  large: "#e06c75" # red

inode:
  valid: "#abb2bf" # foreground
  invalid: "#e06c75" # red

links:
  valid: "#56b6c2" # cyan (distinct from user blue)
  invalid: "#e06c75" # red

tree-edge: "#5fa4e8" # softer blue to keep guides visible but not loud
