name:
  auth: 
  bash: 
  c: 
  cpp: 
  docker: 
  elixir: 
  git: 
  go: 
  go.mod: 
  go.sum: 
  html: 󰌝
  htmx: 
  i3: 
  java: 
  js: 
  license: 󰿃
  lua: 
  .mod: 
  mpv: 
  nvim: 
  vim: 
  ocaml: 
  python: 
  r: 
  readme: 
  rust: 
  sql: 
  steam: 󰓓
  ts: 󰛦
  wezterm: 
  .wine: 󰨡
  zsh: 
  .zshrc: 󱆃
extension:
  ex: 
  go: 
  htmx: 
  js: 
  json: 󰘦
  kbdx: 
  md: 
  mod: 
  rs: 
  sh: 
  zsh: 
