format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_status]
format = "$conflicted$stashed$deleted$renamed$modified$staged$untracked$ahead_behind"
conflicted = "[=](red)[${count}](red) "
stashed = "[*](yellow)[${count}](yellow) "
deleted = "[✘](red)[${count}](red) "
renamed = "[»](blue)[${count}](blue) "
modified = "[!](yellow)[${count}](yellow) "
staged = "[+](green)[${count}](green) "
untracked = "[?](blue)[${count}](blue) "
ahead = "[⇡](cyan)[${count}](cyan) "
behind = "[⇣](cyan)[${count}](cyan) "
diverged = "[⇕](cyan)[⇡${ahead_count}⇣${behind_count}](cyan) "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
