theme = "custom"
force_keyboard_focus = false
timeout = 60

[keybinds]
close = ["Esc"]

[search]
placeholder = "What would you like?"

# Brings duplicates with a terminal symbol for some reason
[builtins.runner]
shell_config = ""
switcher_only = true
hidden = true

[builtins.finder]
use_fd = true
cmd_alt = "xdg_open $(dirname ~/%RESULT%)"
icon = "file"
preview_images = true
prefix = "."

[builtins.calc]
name = "Calculator"
icon = ""
prefix = "="

[builtins.translation]
hidden = true
