# Complement smart-enter plugin
[[mgr.prepend_keymap]]
on = [ "l" ]
run = "plugin smart-enter"
desc = "Enter child directory or open file"

# Drag and drop via dragon
[[mgr.prepend_keymap]]
on = [ "<C-n>" ]
run = '''
	shell 'dragon-drop -x -i -T "$1"' --confirm
	'''
desc = "Click and drag functionality"
